"""Dummy retailer sell-through data, in each retailer's own (messy) layout.

Every retailer reports week-ending-Saturday sales and on-hand inventory, but
each one has its own file shape -- that's why a parser sits in front of the
load:

    R201 Northgate  serial level  CSV   MM/DD/YYYY dates, "$1,234.50" sales, serial numbers with leading zeros
    R202 Summit     SKU level     XLSX  title row above the header, one row per store
    R203 Harbor     style level   CSV   lower-case padded headers, one row per store, a TOTAL row at the bottom
    API  (C102 at R202)           JSON  camelCase fields, cursor-paged (see mock_api/)

Restatements: a retailer re-sends the last 5 weeks in every weekly file, and
the numbers for those weeks drift (returns, late POS uploads) until a week
is 4 weeks old. `as_of` is the week the file was produced; values are a
pure function of (product, store, week, as_of), so any file can be
regenerated byte-for-byte.

Usage:
    python -m data_gen.generate --week-end 2026-09-26 --weeks 12            # history files
    python -m data_gen.generate --week-end 2026-10-03 --weeks 5 --upload    # next weekly drop -> S3 landing
    python -m data_gen.generate --week-end 2026-10-10 --parts 2 --only C101_R201 --upload   # a drop split in 2 files
"""
import argparse
import csv
import io
from datetime import date, datetime, timedelta
from pathlib import Path

from openpyxl import Workbook

from data_gen.catalog import (
    CLIENTS, RETAILERS, UNMAPPED_SERIAL, UNMAPPED_SKU, UNMAPPED_STYLE,
    load_pipelines, skus, stable_rng,
)
from etl.weeks import is_week_end, week_range

LOCAL_OUT = Path(__file__).resolve().parent.parent / "data" / "landing"
STORES = {"sku": [101, 102], "style": [301, 302, 303]}   # serial feeds are already chain-level
RESTATE_WEEKS = 4                                         # numbers settle once a week is 4 weeks old


def _units(client, retailer, key, store, week: date, as_of: date) -> tuple[int, int]:
    """(units sold, units on hand) for one product/store/week as reported in
    the file produced on `as_of`."""
    base = stable_rng(client, retailer, key, store, week)
    units, on_hand = base.randint(0, 40), base.randint(10, 200)
    age = min((as_of - week).days // 7, RESTATE_WEEKS)
    for k in range(1, age + 1):   # each later file adjusts the week a little
        units += stable_rng(client, retailer, key, store, week, k).randint(-2, 3)
    return max(units, 0), on_hand


def normalized_rows(client: str, retailer: str, level: str, weeks: list[date], as_of: date) -> list[dict]:
    """Rows at the retailer's grain, in standard column names (before the
    retailer-specific formatting is applied)."""
    catalog = skus(client)
    rows = []
    for week in weeks:
        if level == "serial":
            keys = [(s.serial, s.unit_price) for s in catalog] + [(UNMAPPED_SERIAL[client], 24.99)]
            for serial, unit_price in keys:
                units, on_hand = _units(client, retailer, serial, 0, week, as_of)
                rows.append({"week_date": week, "client_id": client, "retailer_id": retailer,
                             "product_id": serial, "sales": round(units * unit_price, 2), "inventory": on_hand})
        elif level == "sku":
            keys = [(s.style, s.color, s.size, s.unit_price) for s in catalog]
            keys.append((*UNMAPPED_SKU, catalog[8].unit_price))   # catalog[8] is S03: same style, a color that isn't set up
            for store in STORES["sku"]:
                for style, color, size, unit_price in keys:
                    units, on_hand = _units(client, retailer, (style, color, size), store, week, as_of)
                    rows.append({"week_date": week, "client_id": client, "retailer_id": retailer,
                                 "store": store, "style": style, "color": color, "size": size,
                                 "sales": round(units * unit_price, 2), "inventory": on_hand})
        elif level == "style":
            styles = sorted({s.style for s in catalog}) + [UNMAPPED_STYLE]
            for store in STORES["style"]:
                for style in styles:
                    unit_price = next((s.unit_price for s in catalog if s.style == style), 15.0)
                    units, on_hand = _units(client, retailer, style, store, week, as_of)
                    units *= 4   # a style is ~4 SKUs
                    rows.append({"week_date": week, "client_id": client, "retailer_id": retailer,
                                 "store": store, "style": style,
                                 "sales": round(units * unit_price, 2), "inventory": on_hand * 4})
        else:
            raise ValueError(f"Unknown product level {level!r}")
    return rows


# ---------------------------------------------------------------------------
# Retailer-specific layouts
# ---------------------------------------------------------------------------

def render_r201_csv(rows: list[dict]) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf, quoting=csv.QUOTE_MINIMAL)
    w.writerow(["Week_Date", "Client", "Retailer", "Product_ID", "Sales", "Inventory"])
    for r in rows:
        w.writerow([r["week_date"].strftime("%m/%d/%Y"), r["client_id"], r["retailer_id"],
                    r["product_id"], f"${r['sales']:,.2f}", r["inventory"]])
    return buf.getvalue().encode()


def render_r202_xlsx(rows: list[dict]) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Sell Thru"
    ws.append(["Summit Outfitters - weekly vendor sell-through"])   # title row above the header
    ws.append(["Week Date", "Retailer", "Client", "Store", "Style", "Color", "Size", "Sales $", "Inventory Units"])
    for r in rows:
        ws.append([datetime.combine(r["week_date"], datetime.min.time()), r["retailer_id"], r["client_id"],
                   r["store"], r["style"], r["color"], r["size"], r["sales"], r["inventory"]])
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def render_r203_csv(rows: list[dict]) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow([" week_date ", "retailer", "client", "store", "style", "sales", "inventory"])
    for r in rows:
        w.writerow([r["week_date"].isoformat(), r["retailer_id"], r["client_id"], r["store"],
                    r["style"], f"{r['sales']:.2f}", r["inventory"]])
    # Harbor Mart's export appends a grand-total line -- the parser must drop it.
    w.writerow(["", "", "", "", "TOTAL", f"{sum(r['sales'] for r in rows):.2f}", sum(r["inventory"] for r in rows)])
    return buf.getvalue().encode()


def api_records(rows: list[dict]) -> list[dict]:
    """The mock API's JSON shape (camelCase, ISO dates)."""
    return [{"weekEnding": r["week_date"].isoformat(), "clientId": r["client_id"], "retailerId": r["retailer_id"],
             "storeNumber": r["store"], "style": r["style"], "color": r["color"], "size": r["size"],
             "salesAmount": r["sales"], "onHandUnits": r["inventory"]} for r in rows]


RENDERERS = {"csv": render_r201_csv, "xlsx": render_r202_xlsx}


def render(pipeline: dict, rows: list[dict]) -> bytes:
    if pipeline["retailer_id"] == "R203":
        return render_r203_csv(rows)
    return RENDERERS[pipeline["file_format"]](rows)


def file_name(client: str, retailer: str, week_end: date, ext: str, part: int | None = None) -> str:
    return f"{retailer}_{client}_{week_end:%Y%m%d}{f'_part{part}' if part else ''}.{ext}"


def generate(week_end: date, weeks: int, upload: bool = False, parts: int = 1,
             only: list[str] | None = None) -> list[str]:
    if not is_week_end(week_end):
        raise SystemExit(f"--week-end must be a Saturday, got {week_end} ({week_end:%A})")
    window = week_range(week_end - timedelta(weeks=weeks - 1), week_end)
    written = []
    for p in load_pipelines():
        if p["source_type"] != "s3" or (only and p["pipeline_id"] not in only):
            continue   # the API pipeline pulls from mock_api at run time
        rows = normalized_rows(p["client_id"], p["retailer_id"], p["product_level"], window, as_of=week_end)
        for part in range(1, parts + 1):
            chunk = rows[part - 1::parts]   # a split drop: every part has its own share of the rows
            name = file_name(p["client_id"], p["retailer_id"], week_end, p["file_format"], part if parts > 1 else None)
            body = render(p, chunk)
            if upload:
                from etl import config, s3_io   # only needed for --upload
                key = config.s3_key(p["source_location"], name)
                s3_io.put_bytes(key, body)
                written.append(f"s3://{config.S3_BUCKET}/{key}")
            else:
                path = LOCAL_OUT / p["client_id"] / p["retailer_id"] / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(body)
                written.append(str(path))
    return written


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--week-end", required=True, type=date.fromisoformat, help="last week in the file (a Saturday)")
    ap.add_argument("--weeks", type=int, default=5, help="weeks per file: 12 for history, 5 for a weekly drop")
    ap.add_argument("--upload", action="store_true", help="write to s3://$S3_BUCKET/$RETAIL_ENV/landing/ instead of data/landing/")
    ap.add_argument("--parts", type=int, default=1, help="split each drop into N _partN files")
    ap.add_argument("--only", nargs="*", help="pipeline ids to generate (default: every S3 pipeline)")
    args = ap.parse_args()
    for path in generate(args.week_end, args.weeks, args.upload, args.parts, args.only):
        print(path)


if __name__ == "__main__":
    main()
